import { formatSpecSchema } from "./schema";

const undergraduateSectionRules: FormatSpecSectionRule[] = [
  { key: "cover", label: "封面", required: true, repeatable: false, order: 1 },
  {
    key: "declaration",
    label: "独创性声明",
    required: false,
    repeatable: false,
    order: 2,
  },
  {
    key: "authorization",
    label: "授权书",
    required: false,
    repeatable: false,
    order: 3,
  },
  {
    key: "abstract-zh",
    label: "中文摘要",
    required: true,
    repeatable: false,
    order: 4,
  },
  {
    key: "abstract-en",
    label: "英文摘要",
    required: true,
    repeatable: false,
    order: 5,
  },
  { key: "toc", label: "目录", required: true, repeatable: false, order: 6 },
  { key: "body", label: "正文", required: true, repeatable: false, order: 7 },
  {
    key: "references",
    label: "参考文献",
    required: true,
    repeatable: false,
    order: 8,
  },
  {
    key: "acknowledgements",
    label: "致谢",
    required: false,
    repeatable: false,
    order: 9,
  },
  {
    key: "appendix",
    label: "附录",
    required: false,
    repeatable: true,
    order: 10,
  },
];

const researchSectionRules: FormatSpecSectionRule[] = [
  { key: "cover", label: "封面", required: true, repeatable: false, order: 1 },
  {
    key: "declaration",
    label: "原创性声明",
    required: true,
    repeatable: false,
    order: 2,
  },
  {
    key: "authorization",
    label: "版权授权书",
    required: true,
    repeatable: false,
    order: 3,
  },
  {
    key: "abstract-zh",
    label: "中文摘要",
    required: true,
    repeatable: false,
    order: 4,
  },
  {
    key: "abstract-en",
    label: "英文摘要",
    required: true,
    repeatable: false,
    order: 5,
  },
  { key: "toc", label: "目录", required: true, repeatable: false, order: 6 },
  { key: "body", label: "正文", required: true, repeatable: false, order: 7 },
  {
    key: "references",
    label: "参考文献",
    required: true,
    repeatable: false,
    order: 8,
  },
  {
    key: "acknowledgements",
    label: "致谢",
    required: true,
    repeatable: false,
    order: 9,
  },
  {
    key: "appendix",
    label: "附录",
    required: true,
    repeatable: true,
    order: 10,
  },
];

const undergraduateThesisSpec = formatSpecSchema.parse({
  id: "cn-undergraduate-graduation-thesis-v1",
  name: "中国高校本科毕业论文通用规范",
  description:
    "适用于中文高校本科毕业论文的通用结构校验，可作为模板识别先验与导出前体检基线。",
  thesisType: "graduation-thesis",
  educationLevel: "undergraduate",
  locale: "zh-CN",
  sectionRules: undergraduateSectionRules,
  abstractZhMinLength: 200,
  abstractZhMaxLength: 500,
  abstractEnMinLength: 150,
  abstractEnMaxLength: 500,
  titleMaxLength: 25,
  keywordMinCount: 3,
  keywordMaxCount: 7,
  keywordSeparator: "；",
  keywordSeparatorRequired: false,
  tocRequirePageNumbers: true,
  referenceMinCount: 10,
  foreignReferenceMinCount: 0,
  referenceStyle: "gb-t-7714-2015-numeric",
  titleMaxLevel: 3,
  pageNumberPosition: "right",
  requireContinuousPageNumbers: false,
  allowFrontMatterPageNumberReset: true,
});

const undergraduateGeneralSpec = formatSpecSchema.parse({
  id: "cn-undergraduate-thesis-general-v2",
  name: "中国高校本科论文通用规范（增强版）",
  description:
    "面向多数高校本科论文的增强版结构规范，补充题目/正文长度、目录页码与引用风格等细粒度约束。",
  thesisType: "graduation-thesis",
  educationLevel: "undergraduate",
  locale: "zh-CN",
  sectionRules: undergraduateSectionRules,
  abstractZhMinLength: 300,
  abstractZhMaxLength: 800,
  abstractEnMinLength: 200,
  abstractEnMaxLength: 700,
  titleMinLength: 8,
  titleMaxLength: 30,
  bodyMinLength: 8000,
  bodyMaxLength: 20000,
  keywordMinCount: 3,
  keywordMaxCount: 8,
  keywordSeparator: "；",
  keywordSeparatorRequired: true,
  tocRequirePageNumbers: true,
  referenceMinCount: 15,
  foreignReferenceMinCount: 2,
  referenceStyle: "gb-t-7714-2015-numeric",
  requireCitationStyleConsistency: true,
  titleMaxLevel: 3,
  pageNumberPosition: "center",
  requireContinuousPageNumbers: false,
  allowFrontMatterPageNumberReset: true,
  bodyChapterRules: [
    {
      key: "introduction",
      label: "绪论",
      required: true,
      order: 1,
      minLength: 800,
    },
    {
      key: "methodology",
      label: "研究方法与实现",
      required: true,
      order: 2,
      minLength: 2000,
    },
    {
      key: "analysis",
      label: "结果与分析",
      required: true,
      order: 3,
      minLength: 2000,
    },
    {
      key: "conclusion",
      label: "结论",
      required: true,
      order: 4,
      minLength: 600,
    },
  ],
});

const researchThesisStrictSpec = formatSpecSchema.parse({
  id: "cn-research-thesis-strict-v1",
  name: "中国高校研究型学位论文严格规范",
  description:
    "用于研究型学位论文的严格校验基线，强调章节完整性、引用风格一致性与页码连续性。",
  thesisType: "graduation-thesis",
  educationLevel: "master",
  locale: "zh-CN",
  sectionRules: researchSectionRules,
  abstractZhMinLength: 500,
  abstractZhMaxLength: 1200,
  abstractEnMinLength: 400,
  abstractEnMaxLength: 1000,
  titleMinLength: 12,
  titleMaxLength: 35,
  bodyMinLength: 30000,
  bodyMaxLength: 80000,
  keywordMinCount: 3,
  keywordMaxCount: 5,
  keywordSeparator: "；",
  keywordSeparatorRequired: true,
  tocRequirePageNumbers: true,
  referenceMinCount: 40,
  foreignReferenceMinCount: 15,
  referenceStyle: "gb-t-7714-2015-author-date",
  requireCitationStyleConsistency: true,
  titleMaxLevel: 4,
  pageNumberPosition: "center",
  requireContinuousPageNumbers: true,
  allowFrontMatterPageNumberReset: false,
  bodyChapterRules: [
    {
      key: "introduction",
      label: "绪论",
      required: true,
      order: 1,
      minLength: 2000,
    },
    {
      key: "literature-review",
      label: "文献综述",
      required: true,
      order: 2,
      minLength: 5000,
    },
    {
      key: "methodology",
      label: "研究方法",
      required: true,
      order: 3,
      minLength: 4000,
    },
    {
      key: "experiment",
      label: "实验与结果",
      required: true,
      order: 4,
      minLength: 5000,
    },
    {
      key: "discussion",
      label: "讨论",
      required: true,
      order: 5,
      minLength: 3000,
    },
    {
      key: "conclusion",
      label: "结论与展望",
      required: true,
      order: 6,
      minLength: 1500,
    },
    {
      key: "future-work",
      label: "未来工作",
      required: false,
      order: 7,
      minLength: 800,
    },
  ],
});

export const builtinFormatSpecs: FormatSpec[] = [
  undergraduateThesisSpec,
  undergraduateGeneralSpec,
  researchThesisStrictSpec,
];

export function getBuiltinFormatSpecById(id: string) {
  return builtinFormatSpecs.find((item) => item.id === id);
}

export function getDefaultFormatSpec() {
  return builtinFormatSpecs[0];
}
